#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure build
#


require "autorake/mkconfig"

Autorake.configure {

  with :user,  "www"
  with :group, "www"

  d = case RUBY_PLATFORM
    when /linux/   then "VAR"
    when /freebsd/ then "PREFIX"
  end
  directory :www, "#{d}/www"

  with :location, "hermesdemo"

}

